### DISCUSSION TITLE
Patrol tests runs on ios only after hot reload

### DISCUSSION THREAD

**Discussion by shabanov-krl** [leancodepl/patrol#1582] [Q&A] [answered]
I have several flavors, and I run an example of a patrol test from the documentation, the application is running, but the tests run only after a hot reload. Android is working correctly.

I may have set up the flavors incorrectly. Can you give an example of patrol with flavors?

**Comment by fylyppo** [comment]
Probably your issue is not related to flavors, I'll try to gather some info because IIRC I've seen an issue as yours before, so I come back to you soon. I suppose you did something wrong in iOS setup, so in the meantime try to check once again if you did everything correct.

Regarding flavors:
`pubspec.yaml` could look like this:
```yaml
patrol:
  app_name: Patrol example
  android:
    flavor: dev
    package_name: pl.leancode.patrol.example.dev
  ios:
    flavor: dev
    bundle_id: pl.leancode.patrol.Example.dev
```
the default flavor is set to `dev` in this case, so you don't need to add `--flavor dev` to your `patrol` commands.

In the `MainActivityTest.java` don't add flavor to your app's package.
So in our case we need to provide `package pl.leancode.patrol.example;`.
The rest of the Android configuration stays as without flavors.

According to iOS:
* you need to set `Configurations` for every flavor you want to use with patrol like so:
![image](https://github.com/leancodepl/patrol/assets/63547653/d1e45afb-b14e-46df-8cb7-66ee5d56ea53)
* And disable parallel runs for every flavor you want to use with patrol.
