### ISSUE TITLE
Allowing declaration of several flavors with different packages at patrol section of pubspec.yaml

### ISSUE THREAD

**Issue by proximilian** [leancodepl/patrol#1049]
This new feature-request is а result of discussion #1009.

- So far we can specify a different flavor for Android and iOS, but if there are several flavors for one platform their separate declaration is not possible. 

I have 3 flavors for an app that I have to run test on. My use case is to have them all declared at the pubspec.yaml file's patrol section, because for each of them the packages are different (their names are added different suffix depending on the flavor). In my case package_names are the same as the bundle_ids.
Here is my example:

```
#patrol section if SIT flavor is used
patrol:
  app_name: App Mobile
  android:
    package_name: bg.examplecompany.exampleapp.sit
  ios:
    bundle_id: bg.examplecompany.exampleapp.sit
```
```
#patrol section if UAT flavor is used
patrol:
  app_name: App Mobile
  android:
    package_name: bg.examplecompany.exampleapp.uat
  ios:
    bundle_id: bg.examplecompany.exampleapp.uat
```
The third flavor packages are formulated the same way. Having patrol section with all flavors declared with their specific package_name/bundle_id will enable running automatically the tests for each flavor without the need of manually changing the package_name/bundle_id every time at the pubspec.yaml.

- The scope of the new feature-request can be extended with the following related improvement: It will be very useful if when running `patrol test --target .... --flavor sit` user can have the possibility to parse the arguments especially the flavor one. In my case I want my tests automatically to get that flavor argument and to use it to build the correct main.dart file according to the declared flavor in the command line since in my app I have `main_sit.dart`, `main_dev.dart` and `main_dev.dart`. The argument can be used also to define the correct package_name/bundle_id but if the multiple declaration(mentioned at the top) is allowed at the pubspec.yaml file's patrol section the latter usage will be redundant. That  improvement will be in favor of CI/CD implementation when having apps with several flavors with different package_names for each of them.
