### ISSUE TITLE
Update CI workflows to take advantage of test bundling

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1240]
**Disclaimer**

This issue **is not** about:
- fixing integration tests that are failing (see #1139)
- making tests run on physical iOS on CI (we didn't figure out code signing the RunnerUITests target yet)

### Overview

We want to take advantage of test bundling to present the test results in a better, easier-to-understand way. For example:
- https://github.com/leancodepl/patrol/issues/864
- send results to Slack

### Implementation

We want to run `patrol test` once in the workflow, to run all the bundled tests:

```
patrol test --target integration_test/bundled_test.dart
```

(Currently, we run `patrol test -t <target>` for every Dart test file in the `integration_test` directory. This is bad. That's what bundling is fixing.)

Workflows to be updated:
- [test-android-emulator.yaml](https://github.com/leancodepl/patrol/blob/master/.github/workflows/test-android-emulator.yaml)
- [test-android-device.yaml](https://github.com/leancodepl/patrol/blob/master/.github/workflows/test-android-device.yaml)
- [test-ios-simulator](https://github.com/leancodepl/patrol/blob/master/.github/workflows/test-ios-simulator.yaml)

I recommend @fylyppo to use:
- emulator.wtf (for testing on Android emulators)
- Firebase Test Lab (for testing on physical Android devices)
- directly on GitHub Actions (for testing on iOS simulators)

In particular, we don't want to run on Android emulators on GitHub Actions, because it's been proven to be [flaky and unreliable](#765).

Please bear in mind that bundling is available on `develop`, not on `master`.

**Note 1**

The `bundled_test.dart` must be created manually (this will be fixed in #[1025](https://github.com/leancodepl/patrol/issues/1025)).

**Note 2**

Currently, some tests (= Dart test files in the `integration_test` directory) work only on one platform (e.g. works on Android, fails on iOS). Such workflows are currently commented-out, e.g.:

```yaml
# excerpt from test-android-device.yaml
      - run: ./run_android_testlab integration_test/service_bluetooth_test.dart
        if: ${{ false }} # Not implemented on Android

      - run: ./run_android_testlab integration_test/service_cellular_test.dart
        if: success() || failure()
```

In "pre-bundling Patrol CLI", you could exclude tests to run like this:

```console
patrol test \
  --exclude integration_test/not_you_test.dart \
  --exclude integration_test/you_are_also_yeeted_test.dart
```

We need to re-add this to "post-bundling Patrol CLI" (in [1025](https://github.com/leancodepl/patrol/issues/1025) or [1214](https://github.com/leancodepl/patrol/issues/1214)), but it's not done yet. Therefore, you'll have to work around it manually.
