### ISSUE TITLE
Let developer add aliases and dart-defines for a particular test

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#131]
### Idea v1

Now I got this idea to let developers add aliases to their integration tests.

`maestro.toml` would look like this:

```toml
[drive]
host = 'localhost'
port = 8081
driver = 'test_driver/integration_test.dart'
flavor = 'dev'

[drive.tests]
default = 'integration_test/dualinc_scenario.dart'
demo = 'integration_test/demo_test.dart'
login = 'integration_test/login_test.dart'
hsv = 'integration_test/hsv_scenario.dart'
inc = 'integration_test/dualinc_scenario.dart'

[drive.dart-defines]
CTS_DISABLE_MAP_PRELOADING = 'true'
```

and you'd do `maestro drive inc` or `maestro drive login`.

### Idea v2

Also, it'd be nice to make it possible for dart-defines to be defined per test. This would require some bigger changes to `maestro.toml`. It could look like this:

```toml
[drive]
host = "localhost"
port = 8081
driver = 'test_driver/integration_test.dart'
flavor = 'dev'

  [[drive.tests]]
  name = "default"
  file = "integration_test/demo_test.dart"

  [[drive.tests]]
  name = "login"
  file = "integration_test/login_test.dart"

  [[drive.tests]]
  name = "hsv"
  file = "integration_test/hsv_scenario.dart"

    [drive.tests.dart-defines]
    CTS_DISABLE_MAP_PRELOADING = "true"

  [[drive.tests]]
  name = "inc"
  file = "integration_test/hsv_scenario.dart"

    [drive.tests.dart-defines]
    CTS_DISABLE_MAP_PRELOADING = "true"
```

(PS: I wrote the above in JSON and converted to TOML [using this](https://www.convertsimple.com/convert-json-to-toml/))

### Idea v3

We could let the developer specify the values of `port`, `driver`, and `flavor` for every test (just like I did above with `dart-defines`), and fallback to the global ones (defined at the top of the file).

### Idea v4

@shilangyu [also suggested](https://github.com/leancodepl/aspects/pull/944#discussion_r926688955) that `maestro drive` should automatically discover tests in  `integration_test` directory and let the developer select which one to run. This would conflict with the default `target` specified in `maestro.toml`, so I'd discover tests only if the default `target` is not specified in `maestro.toml`

cc: @shilangyu @jBorkowska @mateuszwojtczak @jakubfijalkowski
