### ISSUE TITLE
Make `patrol drive` auto-discover and run all integration tests

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#144]
Currently `patrol drive` runs the default integration test, which is specified by `target` in `patrol.toml`. Example:

```toml
# patrol.toml
[drive]
host = 'localhost'
port = 8081
target = 'integration_test/demo_test.dart'
driver = 'test_driver/integration_test.dart'
flavor = 'dev'

[drive.dart-defines]
CTS_DISABLE_MAP_PRELOADING = 'true
```

### Scope

- implement automatic test discovery and running in `patrol drive`
- remove `target` argument from `patrol drive` and `target` key from `patrol.toml`

This is extracted from the conclusion of the discussion from https://github.com/leancodepl/patrol/issues/131.

cc @shilangyu @jBorkowska @jakubfijalkowski
