### ISSUE TITLE
There's no CI checking if Patrol finders work with Flutter Web

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1607]
Because of this, issues like #1457 and #1577 arise.

We should run widget tests using Patrol custom finders with ChromeDriver on our CI.

Action draft:

```yaml
prepare-web:
  runs-on: ${{ matrix.os }}
  name: Flutter ${{ matrix.flutter-version }} on  Web on ${{ matrix.os }}
  strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest]
      flutter-version: ['3.10.x']
  defaults:
    run:
      working-directory: packages/patrol/example
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    - name: flutter pub get
      run: flutter pub get
    - name: flutter driver
      run: flutter drive --driver=test_driver/integration_test.dart --target=test/loading_screen_test.dart -d 
chrome
```
