### ISSUE TITLE
Build failures in CI caused by gradlew first run

### ISSUE THREAD

**Issue by richchurcher** [leancodepl/patrol#1837]
### Steps to reproduce

Known issue with a workaround.

<details>
<summary>Sample GitHub Action</summary>

```yaml
name: Android Internal

on:
  push:
    branches:
      - main
    paths:
      - pubspec.yaml

jobs:
  integration:
    environment: internal
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.x'
      - run: dart run build_runner build
      - run: dart pub global activate patrol_cli
      - run: flutter doctor -v && flutter devices
      - run: patrol build android --dart-define AUTH0_DOMAIN=${{secrets.AUTH0_DOMAIN}} --dart-define AUTH0_CLIENT_ID=${{secrets.AUTH0_CLIENT_ID}} --dart-define API_URL=${{secrets.API_URL}}
      - uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'test-963@***.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/289021254472/locations/global/workloadIdentityPools/***/providers/github'
      - uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ***
      - run: |
          gcloud firebase test android run \
            --type instrumentation \
            --use-orchestrator \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --timeout 1m
```

</details>

### Actual results

Gradle fails with error `127` and a stack trace, but with few clues as to the actual cause.

This is an existing bug I believe (see #1301) that still seems to be an issue. Just reproduced with `flutter` 3.13.9 and `patrol_cli` 2.2.1.

Given that Patrol will be frequently used in CI going forward, and usually in this environment the `gradlew` run will always be the first run, I think this behaviour will be confusing when encountered. Perhaps we could have it automatically run a `flutter build apk --config-only` if flutter version is greater than _x_ version (whenever they released `--config-only` for Android targets)?

### Logs

<details>
<summary>Logs</summary>

```shell
Run patrol build android --dart-define AUTH0_DOMAIN=*** --dart-define AUTH0_CLIENT_ID=*** --dart-define API_URL=***
  patrol build android --dart-define AUTH0_DOMAIN=*** --dart-define AUTH0_CLIENT_ID=*** --dart-define API_URL=***
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.13.9-x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/stable-3.13.9-x64/.pub-cache
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
• Building apk with entrypoint test_bundle.dart...
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1[2](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:2)7) (46ms)
Exception: Gradle build failed with code 127
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 127
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#[3](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:3)      BuildAndroidCommand.run (package:patrol_cli/src/commands/build_android.dart:125:7)
<asynchronous suspension>
#[4](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:4)      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#[5](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:5)      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#[6](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:6)      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#[7](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:7)      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#[8](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:8)      main (file:///opt/hostedtoolcache/flutter/stable-3.13.[9](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:10)-x64/.pub-cache/hosted/pub.dev/patrol_cli-2.2.1/bin/main.dart:6:[20](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:8:21))
<asynchronous suspension>
```

</details>

### Patrol version

patrol: 2.2.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Not recorded for this run.
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Run flutter doctor -v && flutter devices
  flutter doctor -v && flutter devices
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x[64](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:6:65)
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.13.9-x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/stable-3.13.9-x64/.pub-cache

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 22.04.3 LTS 6.2.0-1015-azure, locale C.UTF-8)
    • Flutter version 3.13.9 on channel stable at /opt/hostedtoolcache/flutter/stable-3.13.9-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (32 hours ago), 2023-10-25 13:42:25 -0[70](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:6:71)0
    • Engine revision 0545f8705d
    • Dart version 3.[1](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:1).5
    • DevTools version [2](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:2).25.0

[!] Android toolchain - develop for Android devices (Android SDK version [3](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:3)[4](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:4).0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    • Java binary at: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.27.7
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-101[5](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:5)-azure
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
The Flutter CLI developer tool uses Google Analytics to report usage and diagnostic data
along with package dependencies, and crash reporting to send basic crash reports.
This data is used to help improve the Dart platform, Flutter framework, and related tools.

Telemetry is not sent on the very first run.
To disable reporting of telemetry, run this terminal command:

flutter --disable-telemetry.
If you opt out of telemetry, an opt-out event will be sent,
and then no further information will be sent.
This data is collected in accordance with the
Google Privacy Policy (https://policies.google.com/privacy).

2 connected devices:

Linux (desktop) • linux  • linux-x[6](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:6)4      • Ubuntu 22.04.3 LTS 6.2.0-1015-azure
Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.11[7](https://github.com/fgbucket/ui/actions/runs/6663055324/job/18108366973#step:7:7)
```

</details>
