### ISSUE TITLE
Implement retry on failure mechanism

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#2077]
### Use case

I have some tests which depend on external service so I can't reduce flakiness to minimum. That's why I want to retry test on failure. Xcode provides some fields that I can update to achieve retry mechanism but I want to have it also on Android.

### Proposal

My idea is to annotate some tests to retry them a certain number of times

**Comment by lockieRichter** [comment]
This would be fantastic, is this on the roadmap at all?

**Comment by tegankr** [comment]
Agree we need this, would be highly beneficial.

**Comment by tegankr** [comment]
We also tried to implement a JUnit Rule/custom RetryClass but we can't re-run a test twice in the same run due to this issue
https://github.com/leancodepl/patrol/issues/2268

**Comment by jBorkowska** [comment]
Hi @lockieRichter @tegankr, we do have this on our roadmap, though it's not our top priority right now

**Comment by jBorkowska** [comment]
We'll revisit this idea and maybe put this task higher

**Comment by work4montano** [comment]
We can give this higher priority since `testWidgets` already supports retries:

```
void testWidgets(
  String description,
  WidgetTesterCallback callback, {
  bool? skip,
  test_package.Timeout? timeout,
  bool semanticsEnabled = true,
  TestVariant<Object?> variant = const DefaultTestVariant(),
  dynamic tags,
  int? retry,
  LeakTesting? experimentalLeakTesting,
}) {
  assert(
    variant.values.isNotEmpty,
    'There must be at least one value to test in the testing variant.',
  );
```
https://github.com/flutter/flutter/pull/125851

**Comment by praxder** [comment]
Any updates on this? A retry mechanism would be very beneficial since many E2E tests are by nature flaky.

**Comment by m13v** [comment]
retry is necessary for E2E tests but it's a double-edged sword. we had a test suite where adding retry(3) masked a real race condition in our data seeding for almost two months before someone noticed. what worked better for us: retry up to 2x maximum, but also log when a retry actually saves a failing test. then we reviewed the retry logs weekly and fixed the underlying flakiness. the flutter testWidgets retry parameter mentioned above is the right approach since it's per-test. just make sure whoever uses it can also get a report of which tests are retrying most often, otherwise you'll accumulate hidden tech debt.

**Comment by m13v** [comment]
we handle a similar retry-with-tracking pattern in our test runner. the execution and retry orchestration logic is here: https://github.com/assrt-ai/assrt-freestyle/blob/main/src/core/agent.ts - it tracks which tests needed retries and surfaces that in the results.

**Comment by mbenabda** [comment]
@praxder i use marathon as a higher level runner for patrol tests. it provides a plethora of flexibility in running patrol tests. including retry-on-failure. all it needs is: a config file specifying your debug and test apk (patrol build), and an adb server  

https://docs.marathonlabs.io/runner/configuration/retries#fixed-quota-retry-strategy

example Marathonfile:
```yaml
name: "My awesome tests"
outputDir: "build/reports/marathon"
debug: true
ignoreFailures: true
analyticsTracking: false
bugsnagReporting: false
outputConfiguration:
  maxFilename: 255
vendorConfiguration:
  type: "Android"
  autoGrantPermission: true
  applicationPmClear: true
  testApplicationPmClear: true
  testParserConfiguration:
    type: "remote"
    instrumentationArgs:
      listener: "com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer"
  applicationApk: build/app/outputs/apk/myflavor/debug/app-myflavor-debug.apk
  testApplicationApk: build/app/outputs/apk/androidTest/myflavor/debug/app-myflavor-debug-androidTest.apk
  adbServers:
    - host: 127.0.0.1
      port: 5037

uncompletedTestRetryQuota: 100
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 10
  retryPerTestQuota: 1
```
