### ISSUE TITLE
Running patrol tests in Azure CI/CD pipeline

### ISSUE THREAD

**Issue by matanyos** [leancodepl/patrol#2118]
### Use case

i'm trying to use patrol for integration tests in my flutter app.
i am wondering, how can i run patrol tests in azure CI/CD pipeline. 
how i'ts going to run, on what device?

### Proposal

hopefuly, a .yaml file dedicated task, for patrol testing

**Comment by fylyppo** [comment]
Hi, I recommend to use some device farms e.g. [emulatorwtf](https://emulator.wtf), [marathon](https://marathonlabs.io), [FTL](https://firebase.google.com/docs/test-lab/android/get-started). They provide nice dashboards and a lot of features worth to check. Btw setting up emulator or simulator instance on Azure hosted machines wouldn't be efficient and I suppose your tests may fail because of poor device performance.
Regarding task - we don't have any plans to create it

**Comment by matanyos** [comment]
Thank you @fylyppo 
Can you provide steps to integrate patrol with Firebase test lab?

**Comment by Noxiver** [comment]
@matanyos u can use this [instruction](https://patrol.leancode.co/ci/firebase-test-lab)
It was helpful for me

**Comment by matanyos** [comment]
@Noxiver thank you!

**Comment by Wreos** [comment]
I run my project's e2e tests in Firebase by running Azure Pipeline.
There is example of pipeline, i hope it helps you :) 

```yaml
name: Android E2E Tests run
variables:
  flutterVersion: '3.19.0'
  patrolVersion: '2.6.4'
  projectDirectory: 'TestApp'
  flavor: $(APP_FLAVOR)

schedules:
  - cron: "0 2 * * *"
    displayName: Nightly Android E2E tests build
    branches:
      include:
        - dev

trigger:
  - master

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        pool:
          vmImage: 'macOS-latest'
        steps:
          - script: xcodebuild -version
            displayName: 'Check Xcode Version'
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - task: FlutterInstall@0
            inputs:
              channel: 'stable'
              mode: 'auto'
              version: 'custom'
              customVersion: $(flutterVersion)

          - task: DownloadSecureFile@1
            name: authkey
            displayName: 'Download Service Account Key'
            inputs:
              secureFile: 'testapp-firebase-test-lab.json'
              retryCount: '2'

          - task: FlutterCommand@0
            displayName: 'Flutter pub get'
            inputs:
              projectDirectory: $(Build.SourcesDirectory)
              arguments: 'pub get'

          - task: FlutterCommand@0
            displayName: 'Flutter Generate phrase code'
            inputs:
              projectDirectory: $(Build.SourcesDirectory)
              arguments: 'pub run phrase'

          - template: templates/generate-env.yml

          - task: CmdLine@2
            displayName: 'Flutter packages: Check and generate code'
            inputs:
              script: |
                export PATH=$(FlutterToolPath):$PATH
                ./build_packages.sh
              workingDirectory: 'pipeline'

          - task: FlutterCommand@0
            displayName: 'Flutter: Update icons'
            inputs:
              projectDirectory: $(Build.SourcesDirectory)
              arguments: 'pub run flutter_launcher_icons:main'        

          - task: CmdLine@2
            displayName: 'Make test build with patrol'
            inputs:
              script: |
                dart pub global activate patrol_cli $(patrolVersion)
                flutter build apk --debug --flavor $(flavor)
                ~/.pub-cache/bin/patrol build android --flavor $(flavor) --dart-define=integration_test=true
              workingDirectory: '$(Build.SourcesDirectory)'

          - task: CmdLine@2
            displayName: 'Install Google cloud'
            inputs:
              script: 'brew install --cask google-cloud-sdk'
              workingDirectory: '$(Agent.ToolsDirectory)'

          - task: CmdLine@2
            displayName: 'Activate service account and set active project'
            inputs:
              script: |
                gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
                gcloud config set project testapp 

          - task: CmdLine@2
            displayName: 'Run e2e tests on Android'
            inputs:
              script: 'gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/$(flavor)/debug/app-$(flavor)-debug.apk --client-details=matrixLabel="Android E2E test run" --test build/app/outputs/apk/androidTest/$(flavor)/debug/app-$(flavor)-debug-androidTest.apk --device model=$(DEVICE_MODEL),version=$(ANDROID_API),locale=de,orientation=portrait --timeout 20m --use-orchestrator --environment-variables clearPackageData=true'
              workingDirectory: '$(Build.SourcesDirectory)'
```
