### ISSUE TITLE
Patrol test fails on Codemagic on "Building apk with entrypoint test_bundle.dart..." stage

### ISSUE THREAD

**Issue by nursultan-akhmetzhanov** [leancodepl/patrol#2204]
### Steps to reproduce

Here is the sanitised YAML configuration of the `codemagic.yaml` file:

```yaml
definitions:
  instance_mac_mini_m2: &instance_mac_mini_m2
    instance_type: mac_mini_m2
    max_build_duration: 60
  instance_mac_mini_m1: &instance_mac_mini_m1
    instance_type: mac_mini_m1
    max_build_duration: 60
  instance_linux: &instance_linux
    instance_type: linux
    max_build_duration: 60
  env_settings: &env_settings
    flutter: 3.16.9
    xcode: latest
    cocoapods: default
    groups:
      - ExampleGroup
  production_triggering: &production_triggering
    events:
      - push
      - tag
    branch_patterns:
      - pattern: release/production
        include: true
    tag_patterns:
      - pattern: production-release
        include: true
  test_triggering: &test_triggering
    events:
      - tag
    tag_patterns:
      - pattern: test-release
        include: true
  cache: &cache_paths
    cache_paths:
      - $HOME/Library/Caches/CocoaPods
      - $HOME/.gradle/caches
      - $FLUTTER_ROOT/.pub-cache
  artifacts: &flutter_artifacts
    - build/**/outputs/bundle/**/*.aab
    - build/ios/ipa/*.ipa
    - build/**/outputs/**/mapping.txt
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/Runner.app.dSYM
    - symbols/*.symbols
  app_store_connect_credentials: &app_store_connect_credentials
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  google_play: &google_play
    credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    track: internal
  scripts:
    - &set_up_ios_code_signing
      name: Set up iOS code signing
      script: |
        keychain initialize
        keychain add-certificates
    - &install_dependencies
      name: Install dependencies
      script: |
        flutter pub cache repair
        flutter pub get
        flutter pub get ./apps/widgetbook
        dart pub get --directory scripts/set_version
    - &generate_localizations
      name: Generate localizations
      script: |
        set -e
        flutter pub run intl_utils:generate
        dart scripts/arb_checker.dart
    - &analyze_and_test
      name: Analyze and test
      script: |
        set -e
        flutter analyze
        flutter test
    - &set_app_version
      name: Set app version
      script: |
        dart run scripts/set_version/bin/set_version.dart
    - &generate_test_release_notes
      name: Generate test build release notes
      script: ./scripts/release_notes.sh
    - &build_ios
      name: Build iOS
      script: |
        set -e
        set -x
        xcode-project use-profiles
        flutter build ipa --export-options-plist ~/export_options.plist --flavor $FLAVOR --dart-define-from-file $DART_DEFINE_FILE -t $TARGET --split-debug-info=symbols
    - &check_mock_data
      name: Check mock data is compiled out
      script: scripts/check_mock_data.sh
    - &build_android
      name: Build Android
      script: |
        set -e
        set -x
        flutter build appbundle --release --flavor $FLAVOR --dart-define-from-file $DART_DEFINE_FILE -t $TARGET --split-debug-info=symbols
    - &upload_debug_symbols
      name: Upload debug symbols
      script: |
        yq -i '.name = strenv(BUNDLE_IDENTIFIER)' pubspec.yaml
        flutter pub get
        flutter packages pub run sentry_dart_plugin
    - &install_patrol
      name: Install patrol and its dependencies
      script: |
        dart pub global activate patrol_cli
        patrol doctor
    - &start_android_emulator
      name: Start Android emulator
      script: |
        cd $ANDROID_HOME/tools
        emulator -avd emulator &
        adb wait-for-device
    - &patrol_integration_tests
      name: Integration tests using patrol
      script: |
        patrol test -t integration_test/basic_order_test.dart --flavor testFlavor --verbose
        test_report: build/app/outputs/androidTest-results/connected/*.xml

workflows:
  example-integration-test:
    name: Example Integration Test
    <<: *instance_linux
    triggering: *test_triggering
    environment:
      <<: *env_settings
      vars:
        TARGET: lib/main_test.dart
        FLAVOR: exampletest
        DART_DEFINE_FILE: env-example-test.json
        BUNDLE_IDENTIFIER: com.example.example.ios.dev
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.example.ios.dev
      android_signing:
        - example_test
    cache: *cache_paths
    scripts:
      # - *set_up_ios_code_signing
      - *install_dependencies
      - *generate_localizations
      # - *analyze_and_test
      # - *set_app_version
      - *generate_test_release_notes
      # - *build_ios
      - *build_android
      - *upload_debug_symbols
      - *install_patrol
      - *start_android_emulator
      - *patrol_integration_tests
    artifacts: *flutter_artifacts
    publishing:
      <<: *publish_notifications
      google_play: *google_play
      app_store_connect:
        <<: *app_store_connect_credentials
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - External
```

Here are the contents of `android/app/build.gradle` file:

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def dartDefines = [:];
if (project.hasProperty('dart-defines')) {
    // Decode dart-defines, which are comma-separated and encoded in Base64, and store them in a variable.
    dartDefines = dartDefines + project.property('dart-defines')
            .split(',')
            .collectEntries { entry ->
                def pair = new String(entry.decodeBase64(), 'UTF-8').split('=', 2)
                [(pair.first()): pair.last()]
            }
}

android {
    ndkVersion "25.1.8937393"

    signingConfigs {
       release {
           if (System.getenv()['CI']) { // Used when building on CI
               storeFile file(System.getenv()['CI_KEYSTORE_PATH'])
               storePassword System.getenv()['CI_KEYSTORE_PASSWORD']
               keyAlias System.getenv()['CI_KEY_ALIAS']
               keyPassword System.getenv()['CI_KEY_PASSWORD']
           } else {
               keyAlias keystoreProperties['keyAlias']
               keyPassword keystoreProperties['keyPassword']
               storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
               storePassword keystoreProperties['storePassword']
           }
       }
    }

    flavorDimensions "flavor-type"

    productFlavors {
        exampleFlavor1 {
            dimension "flavor-type"
        }
        exampleFlavor2 {
            dimension "flavor-type"
        }
        exampleFlavor3 {
            dimension "flavor-type"
        }
        exampleFlavor4 {
            dimension "flavor-type"
        }
        exampleFlavor5 {
            dimension "flavor-type"
        }
        exampleFlavor6 {
            dimension "flavor-type"
        }
        exampleFlavor7 {
            dimension "flavor-type"
        }
        exampleFlavor8 {
            dimension "flavor-type"
        }
        exampleFlavor9 {
            dimension "flavor-type"
        }
        exampleFlavor10 {
            dimension "flavor-type"
        }
    }

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId dartDefines.ANDROID_APPLICATION_ID
        resValue "color", "ic_launcher_background", dartDefines.ANDROID_LAUNCHER_BACKGROUND
        resValue "string", "app_name", dartDefines.APP_NAME
        resValue "string", "ANDROID_ASSET_LINK_STATEMENT", dartDefines.ANDROID_ASSET_LINK_STATEMENT
        resValue "string", "FB_APP_ID", dartDefines.FB_APP_ID
        resValue "string", "FB_CLIENT_TOKEN", dartDefines.FB_CLIENT_TOKEN
        minSdkVersion 24
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "pl.leancode.patrol.PatrolJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            multiDexEnabled true
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled false
            shrinkResources false
            multiDexEnabled false
        }
    }

    testOptions {
        execution "ANDROIDX_TEST_ORCHESTRATOR"
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    androidTestUtil "androidx.test:orchestrator:1.4.2"
}

apply plugin: 'com.google.gms.google-services'
```

Configuration not related to this issue was removed from the codeblock above

### Actual results

The tests run well on my local machine on both android and iOS emulators. But for an unknown reasons tests fail on the first step of the `patrol test`. Gradle complains about the files not being detected or found at all:

```
: > Task :app:compileFlutterBuildTestFlavorDebug
Error: Couldn't resolve the package 'example_apps' in 'package:example_apps/main_test.dart'.
Error: Couldn't resolve the package 'example_apps' in 'package:example_apps/keys.dart'.
```

More in the _logs_ section.

### Logs

<details>
<summary>Logs: codemagic error logs</summary>

The `patrol test --flavor exampletest -t integration_test/basic_order_test.dart` command failed with the logs below

The logs were sanitised, sensitive data was removed
```
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 1 test target(s)
Received test target: /home/builder/clone/integration_test/basic_order_test.dart
Generated entrypoint /home/builder/clone/integration_test/test_bundle.dart with 1 bundled test(s)
Received Android flavor: testFlavor
Received iOS flavor: testFlavor
Received macOS flavor: testFlavor
$ flutter --no-version-check --suppress-analytics devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Received 26 --dart-define(s) (16 custom, 10 internal)
Received custom --dart-define: APP_FLAVOR
Received custom --dart-define: APP_NAME
Received custom --dart-define: IOS_URL_SCHEME
Received custom --dart-define: IOS_GOOGLE_SERVICES_PLIST
Received custom --dart-define: IOS_GOOGLE_REVERSED_CLIENT_ID
Received custom --dart-define: IOS_LAUNCH_SCREEN
Received custom --dart-define: ASSETCATALOG_COMPILER_APPICON_NAME
Received custom --dart-define: IOS_LAUNCH_STATUS_BAR_STYLE
Received custom --dart-define: IOS_ASSOCIATED_DOMAIN_WEB_CREDENTIALS_RESTIS
Received custom --dart-define: IOS_ASSOCIATED_DOMAIN_APP_LINKS_RESTIS
Received custom --dart-define: IOS_ASSOCIATED_DOMAIN_APP_LINKS_BRAND
Received custom --dart-define: ANDROID_APPLICATION_ID
Received custom --dart-define: ANDROID_LAUNCHER_BACKGROUND
Received custom --dart-define: ANDROID_ASSET_LINK_STATEMENT
Received custom --dart-define: FB_APP_ID
Received custom --dart-define: FB_CLIENT_TOKEN
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.dev
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.app.ios.dev
Received internal --dart-define: PATROL_MACOS_APP_BUNDLE_ID=com.example.macos.app.dev
Received internal --dart-define: PATROL_ANDROID_APP_NAME=ExampleApp
Received internal --dart-define: PATROL_IOS_APP_NAME=ExampleApp
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleTestFlavorDebug -Ptarget=/home/builder/clone/integration_test/test_bundle.dart -Pdart-defines=QVBQX0ZMQVZPUj10ZXN0Rmxhdm9y, QVBQX05BTUU9VGVzdCBGTEFWT1I=, SU9TX1VSTF9TQ0hFTUU9ZXhhbXBsZXRlc3Q=, SU9TX0dPT0dMRV9TRVJWSUNFU19QTElTVD1Hb29nbGVTZXJ2aWNlLUluZm8tdGVzdC5wbGlzdA==, SU9TX0dPT0dMRV9SRVZFUlNFRF9DTElFTlRfSUQ9Y29tLmdvb2dsZXVzZXJjb250ZW50LmFwcHMuNTg0MDAwMDAxNjUyLWhhNG9nNGUyOW50anR1MGdidTYxMDc3MDVndmNtYzZ0, SU9TX0xBVU5DSF9TQ1JFRU49TGF1bmNoU2NyZWVuLXRlc3Q=, QVNTRVRDQVRBTE9HX0NPTVBJTEVSX0FQUElDT05fTkFNRT1BcHBJY29uLXRlc3Q=, SU9TX0xBVU5DSF9TVEFUVVNfQkFSX1NUWUxFPVVJU3RhdHVzQmFyU3R5bGVEYXJrQ29udGVudA==, SU9TX0FTU09DSUFURURfRE9NQUlOX1dFQl9DUkVERU5USUFMU19SRVNUSVM9d2ViY3JlZGVudGlhbHM6YXBwLXRlc3QuZXhhbXBsZS5jb2RlbWF0ZS5jb20=, SU9TX0FTU09DSUFURURfRE9NQUlOX0FQUF9MSU5LU19SRVNUSVM9YXBwbGlua3M6YXBwLXRlc3QuZXhhbXBsZS5jb2RlbWF0ZS5jb20=, SU9TX0FTU09DSUFURURfRE9NQUlOX0FQUF9MSU5LU19CUkFORD1hcHBsaW5rczpidXJnZXJraW5nLmV4YW1wbGU=, QU5EUk9JRF9BUFBMSUNBVElPTl9JRD1jb20uZXhhbXBsZS5hcHAuYW5kcm9pZC5kZXY=, QU5EUk9JRF9MQVVOQ0hFUl9CQUNLR1JPVU5EPSNmN2ViZGE=, QU5EUk9JRF9BU1NFVF9MSU5LX1NUQVRFTUVOVD1beyJpbmNsdWRlIjogImh0dHBzOi8vYXBwLXRlc3QuZXhhbXBsZS5jb2RlbWF0ZS5jb20vLndlbGwta25vd24vYXNzZXRsaW5rcy5qc29uIn1d, RkJfQVBQX0lEPTI4MzExMTIwODExODk2Mw==, RkJfQ0xJRU5UX1RPS0VOPTYyYTQxM2Q0YTZlYWQzNWYzZWViYzljOGVmYTgzMzQz, UEFUUk9MX1dBSVQ9MA==, UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUuZm9vZGFuZGV2ZW50cy5kZXY=, UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuYXBwLmlvcy5kZXY=, UEFUUk9MX01BQ09TX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUubWFjb3MuYXBwLmRldg==, UEFUUk9MX0FORFJPSURfQVBQX05BTUU9RXhhbXBsZQ==, UEFUUk9MX0lPU19BUFBfTkFNRT1FeGFtcGxl, SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl, UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl, UEFUUk9MX1RFU1RfU0VSVkVSX1BPUlQ9ODA4MQ==, UEFUUk9MX0FQUF9TRVJWRVJfUE9SVD04MDgy -Papp-server-port=8082 -Ptest-server-port=8081

: 
: Welcome to Gradle 7.5!
: 
: Here are the highlights of this release:
:  - Support for Java 18
:  - Support for building with Groovy 4
:  - Much more responsive continuous builds
:  - Improved diagnostics for dependency resolution
: 
: For more details see https://docs.gradle.org/7.5/release-notes.html
: 
: WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
: 
: This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33
: 
: This warning can be suppressed by adding
:     android.suppressUnsupportedCompileSdk=34
: to this project's gradle.properties
: 
: The build will continue, but you are strongly encouraged to update your project to
: use a newer Android Gradle Plugin that has been tested with compileSdk = 34
: > Task :app:preBuild UP-TO-DATE
: > Task :app:preTestFlavorDebugBuild UP-TO-DATE
: > Task :app:mergeTestFlavorDebugNativeDebugMetadata NO-SOURCE
: > Task :adyen_dropin:preBuild UP-TO-DATE
: > Task :adyen_dropin:preDebugBuild UP-TO-DATE
: > Task :adyen_dropin:compileDebugAidl NO-SOURCE
: > Task :adyen_dropin:checkKotlinGradlePluginConfigurationErrors
: > Task :adyen_dropin:compileDebugRenderscript NO-SOURCE
: > Task :adyen_dropin:generateDebugBuildConfig
: > Task :adyen_dropin:generateDebugResValues
: > Task :adyen_dropin:generateDebugResources
: > Task :adyen_dropin:packageDebugResources
: > Task :adyen_dropin:parseDebugLocalResources
: > Task :adyen_dropin:javaPreCompileDebug
: > Task :android_id:preBuild UP-TO-DATE
: > Task :android_id:preDebugBuild UP-TO-DATE
: > Task :android_id:compileDebugAidl NO-SOURCE
: > Task :android_id:checkKotlinGradlePluginConfigurationErrors
: 
: > Task :adyen_dropin:processDebugManifest
: package="com.codemate.adyen_dropin" found in source AndroidManifest.xml: /home/builder/.pub-cache/git/example-flutter-adyen-523a71247ee4f87b146128f28ad3427f09796a3d/android/src/main/AndroidManifest.xml.
: Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
: Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
: This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
: 
: > Task :android_id:compileDebugRenderscript NO-SOURCE
: > Task :android_id:generateDebugBuildConfig
: > Task :android_id:generateDebugResValues
: > Task :android_id:generateDebugResources
: > Task :android_id:packageDebugResources
: > Task :android_id:parseDebugLocalResources
: 
: > Task :android_id:processDebugManifest
: package="dev.fluttercommunity.android_id" found in source AndroidManifest.xml: /home/builder/.pub-cache/hosted/pub.dev/android_id-0.3.6/android/src/main/AndroidManifest.xml.
: Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
: Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
: This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
: 
: > Task :android_id:generateDebugRFile
: > Task :android_id:javaPreCompileDebug
: > Task :adyen_dropin:generateDebugRFile
: > Task :android_id:compileDebugKotlin
: 
: > Task :adyen_dropin:compileDebugKotlin
: w: file:///home/builder/.pub-cache/git/example-flutter-adyen-523a71247ee4f87b146128f28ad3427f09796a3d/android/src/main/kotlin/com/codemate/adyen_dropin/AdyenDropinPlugin.kt:238:53 'LIVE: Environment!' is deprecated. Deprecated in Java
: 
: > Task :app:compileFlutterBuildTestFlavorDebug
Error: Couldn't resolve the package 'example_apps' in 'package:example_apps/main_test.dart'.
Error: Couldn't resolve the package 'example_apps' in 'package:example_apps/keys.dart'.
integration_test/basic_order_test.dart:5:8: Error: Not found: 'package:example_apps/main_test.dart'
	import 'package:example_apps/main_test.dart' as app;
	       ^
integration_test/basic_order_test.dart:6:8: Error: Not found: 'package:example_apps/keys.dart'
	import 'package:example_apps/keys.dart';
	       ^
integration_test/basic_order_test.dart:12:11: Error: Method not found: 'main'.
	      app.main();
	          ^^^^
integration_test/basic_order_test.dart:55:27: Error: Undefined name 'K'.
	      await $.enterText($(K.resSearchTextField), 'Cat');
	                          ^
	Unhandled exception:
	FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aexample_apps%2Fmain_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
	#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
	#1      asFileUri (package:vm/kernel_front_end.dart:732:37)
	#2      writeDepfile (package:vm/kernel_front_end.dart:870:21)
	<asynchronous suspension>
	#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:676:9)
	<asynchronous suspension>
	#4      starter (package:frontend_server/starter.dart:102:12)
	<asynchronous suspension>
	#5      main (file:///b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
	<asynchronous suspension>
	
	Target kernel_snapshot failed: Exception
	
	
	FAILURE: Build failed with an exception.
	
	* Where:
	Script '/home/builder/programs/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350
	
	* What went wrong:
	Execution failed for task ':app:compileFlutterBuildTestFlavorDebug'.
	> Process 'command '/home/builder/programs/flutter/bin/flutter'' finished with non-zero exit value 1
	
	* Try:
	> Run with --stacktrace option to get the stack trace.
	: 
	: > Task :app:compileFlutterBuildTestFlavorDebug FAILED
	: 
	: Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
	: 
	: You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
	: 
	: See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
	: 19 actionable tasks: 19 executed
	> Run with --info or --debug option to get more log output.
	> Run with --scan to get full insights.
	
	* Get more help at https://help.gradle.org
	
	BUILD FAILED in 25s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (25.8s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:279:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:213:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:347:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:291:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///home/builder/.pub-cache/hosted/pub.dev/patrol_cli-2.7.0/bin/main.dart:6:20)
<asynchronous suspension>

/tmp/build_script_12_1_0d18glgf: line 4: test_report:: command not found


Build failed :|
Step 12 script `Integration tests using patrol` exited with status code 127
```

</details>

### Patrol version

patrol_finders: ^2.0.1
patrol: ^3.6.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol doctor output on my machine
```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.16.5 • channel stable
Android: 
• Program adb found in /Users/nursultan_akhmetzhanov/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/nursultan_akhmetzhanov/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

Patrol doctor output found on CI/CD
```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.16.9 • channel stable
Android: 
• Program adb found in /usr/local/share/android-sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /usr/local/share/android-sdk
```
</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

Flutter doctor output on CI/CD
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 20.04.6 LTS 5.15.0-1040-gcp, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

Flutter doctor output on my machine

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>
