### ISSUE TITLE
Add accepting/denying runtime permissions on Android

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#231]
### Structure of the Android permission dialog

**Samsung SM X205 API 30**

```
TextView:
  package: com.google.android.permissioncontroller
  id: com.android.permissioncontroller:id/permission_message
  text: Allow REDACTED to access this device’s location?

Button:
  package: com.google.android.permissioncontroller
  id: com.android.permissioncontroller:id/permission_allow_foreground_only_button
  text: While using the app

Button:
  package: com.google.android.permissioncontroller
  id: com.android.permissioncontroller:id/permission_allow_one_time_button
  text: Only this time

Button:
  package: com.google.android.permissioncontroller
  id: com.android.permissioncontroller:id/permission_deny_button
  text: Don't allow
```

**Pixel C emulator API 31**

same as _Samsung SM X205 API 30_

**Pixel C emulator API 33**

same as _Samsung SM X205 API 30_
