### ISSUE TITLE
patrol test: Uninstalling the app after the test was run

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#816]
To uninstall an app, we need to know its package name / bundle ID.

The easiest way to accomplish this is to ask the user to specify these values in `pubspec.yaml`:

**Example**
```yaml
# pubspec.yaml

dependencies:
  bloc: ^7.2.0
  # ...

dev_dependencies:
  patrol: ^1.0.0
  # ...

patrol:
  android_app_id: pl.leancode.patrol.example
  ios_app_id: pl.leancode.patrol.Example
  # macos, windows in the future?
```

or:

```yaml
patrol:
  app_ids:
    android: pl.leancode.patrol.example
    ios: pl.leancode.patrol.Example
    # more in the future?
```

cc @mateuszwojtczak

**Comment by bartekpacia** [comment]
```yaml
patrol:
  android:
    app_id: pl.leancode.patrol.example
    app_name: "Patrol example"
  ios:
    app_id: pl.leancode.patrol.Example
    app_name: "Patrol example"
```

Adding app name will unblock #157

**Comment by bartekpacia** [comment]
Do we also want to uninstall the app if it is already present on the device?

**Comment by bartekpacia** [comment]
Reopening because `pubspec.yaml` fields are not implemented yet.

**Comment by crisboarna** [comment]
Hi, I am looking at using your testing framework. This issue solution seems to not cover the case of flavours ? If you want to run Android flavours tests it will not be a static package name, there will be a suffix added to it. Is that scenario covered ?

**Comment by bartekpacia** [comment]
Hi @crisboarna, thanks for taking a look at us! :)

If you configured your app to have a `app_id` according to the flavor, you'll be able to specify this. For example, let's say that your `app_id` is `com.crisboarna.calendar` and it has 3 flavors: `dev`, `staging`, and `prod`, and that you wish to run your integration tests with `staging` flavor. Then you'll be able to do:

```yaml
patrol:
  android:
    app_id: com.crisboarna.calendar.staging
    app_name: Awesome Calendar
```

To run these tests (with automatic uninstall), you'll execute:

```console
patrol test --flavor staging
```

Does it solve your use case?
